"""
progress.py
Scans all topic folders and generates PROGRESS.md with checkboxes.
A question is marked as "done" if its folder contains a non-empty .java or .py file
(other than the default TODO template).

Usage:
    python progress.py
"""

import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))

TOPICS = [
    ("Arrays",                  "arrays"),
    ("Strings",                 "strings"),
    ("Linked List",             "linked-list"),
    ("Stack & Queue",           "stack-queue"),
    ("Trees",                   "trees"),
    ("Graph",                   "graph"),
    ("Dynamic Programming",     "dynamic-programming"),
    ("Recursion & Backtracking","recursion-backtracking"),
]


def is_solved(folder_path: str) -> bool:
    """
    Returns True if the folder has at least one .java or .py file
    that contains actual code (not just the default TODO template).
    """
    for fname in os.listdir(folder_path):
        if fname.endswith(".java") or fname.endswith(".py"):
            fpath = os.path.join(folder_path, fname)
            try:
                content = open(fpath, encoding="utf-8").read().strip()
            except Exception:
                continue
            # Skip completely empty files
            if not content:
                continue
            # Skip pure template files (only TODO comment, no real logic)
            lines = [l.strip() for l in content.splitlines() if l.strip()]
            non_template = [
                l for l in lines
                if not l.startswith("//")
                and not l.startswith("#")
                and l not in ("class Solution {", "}", "pass",
                              "class Solution:", "public void solve() {",
                              "def solve(self):")
                and "TODO" not in l
            ]
            if non_template:
                return True
    return False


def get_title_from_md(folder_path: str, lc_num: str) -> str:
    """Extract problem title from the .md file in the folder."""
    for fname in os.listdir(folder_path):
        if fname.endswith(".md"):
            fpath = os.path.join(folder_path, fname)
            try:
                for line in open(fpath, encoding="utf-8"):
                    line = line.strip()
                    if not line:
                        continue
                    # Standard format: # Two Sum
                    if line.startswith("# "):
                        return line[2:].strip()
                    # Daily streak format: "396. Rotate Function"
                    m = re.match(r"^\d+\.\s+(.+)$", line)
                    if m:
                        return m.group(1).strip()
                    # Only check first non-empty line
                    break
            except Exception:
                pass
    return f"LC-{lc_num}"


def parse_lc_number(folder_name: str) -> str:
    """Extract the LC number from folder name like LC-42 or LC-42(4thMay26)."""
    m = re.match(r"LC-(\d+)", folder_name)
    return m.group(1) if m else folder_name


def scan_topic(topic_path: str):
    """Returns list of (lc_num, title, solved) sorted by lc_num."""
    results = []
    if not os.path.isdir(topic_path):
        return results
    for entry in sorted(os.listdir(topic_path)):
        full = os.path.join(topic_path, entry)
        if not os.path.isdir(full):
            continue
        if not entry.startswith("LC-"):
            continue
        lc_num = parse_lc_number(entry)
        title = get_title_from_md(full, lc_num)
        solved = is_solved(full)
        results.append((int(lc_num) if lc_num.isdigit() else 0, lc_num, title, solved))
    results.sort(key=lambda x: x[0])
    return results


def build_progress_md():
    lines = []
    lines.append("# DSA Progress Tracker")
    lines.append("")
    lines.append("> Auto-generated by `progress.py` — run it anytime to refresh.")
    lines.append("")

    total_done = 0
    total_all = 0

    topic_summaries = []

    # ── Topic sections ──────────────────────────────────────────────
    for display_name, folder in TOPICS:
        topic_path = os.path.join(ROOT, folder)
        questions = scan_topic(topic_path)

        done = sum(1 for _, _, _, solved in questions if solved)
        total = len(questions)
        total_done += done
        total_all += total

        topic_summaries.append((display_name, done, total))

        bar_filled = int((done / total * 20)) if total else 0
        bar = "█" * bar_filled + "░" * (20 - bar_filled)
        pct = f"{done/total*100:.0f}%" if total else "0%"

        lines.append(f"## {display_name}  `{done}/{total}` {pct}")
        lines.append(f"`{bar}`")
        lines.append("")
        lines.append("| # | Problem | Status |")
        lines.append("|---|---------|--------|")

        for _, lc_num, title, solved in questions:
            checkbox = "✅" if solved else "⬜"
            lc_link = f"[LC-{lc_num}](https://leetcode.com/problems/{title.lower().replace(' ', '-')}/)"
            lines.append(f"| {lc_num} | {title} | {checkbox} |")

        lines.append("")

    # ── Summary table ────────────────────────────────────────────────
    summary_lines = []
    summary_lines.append("## Summary")
    summary_lines.append("")
    summary_lines.append("| Topic | Done | Total | Progress |")
    summary_lines.append("|-------|------|-------|----------|")

    for display_name, done, total in topic_summaries:
        bar_filled = int((done / total * 10)) if total else 0
        bar = "█" * bar_filled + "░" * (10 - bar_filled)
        pct = f"{done/total*100:.0f}%" if total else "0%"
        summary_lines.append(f"| {display_name} | {done} | {total} | `{bar}` {pct} |")

    overall_pct = f"{total_done/total_all*100:.0f}%" if total_all else "0%"
    summary_lines.append(f"| **Total** | **{total_done}** | **{total_all}** | **{overall_pct}** |")
    summary_lines.append("")

    # Assemble: summary first, then topics
    final = []
    final.append("# DSA Progress Tracker")
    final.append("")
    final.append("> Auto-generated by `progress.py` — run it anytime to refresh.")
    final.append("")
    final += summary_lines

    # Then each topic detail
    for display_name, folder in TOPICS:
        topic_path = os.path.join(ROOT, folder)
        questions = scan_topic(topic_path)

        done = sum(1 for _, _, _, solved in questions if solved)
        total = len(questions)

        bar_filled = int((done / total * 20)) if total else 0
        bar = "█" * bar_filled + "░" * (20 - bar_filled)
        pct = f"{done/total*100:.0f}%" if total else "0%"

        final.append(f"## {display_name}  `{done}/{total}` — {pct}")
        final.append(f"`{bar}`")
        final.append("")
        final.append("| # | Problem | Status |")
        final.append("|---|---------|--------|")

        for _, lc_num, title, solved in questions:
            checkbox = "✅" if solved else "⬜"
            final.append(f"| {lc_num} | {title} | {checkbox} |")

        final.append("")

    return "\n".join(final)


if __name__ == "__main__":
    md = build_progress_md()
    out_path = os.path.join(ROOT, "PROGRESS.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"✅  PROGRESS.md updated at {out_path}")
